# Generated by Django 6.0.2 on 2026-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("outcome", "Outcome"),
                            ("impact", "Impact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_value", models.IntegerField(default=0)),
                ("actual_value", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "proof_document",
                    models.FileField(
                        blank=True, null=True, upload_to="indicator_proofs/"
                    ),
                ),
            ],
        ),
    ]
