# Generated by Django 6.0.2 on 2026-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("school", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("age_group", models.CharField(blank=True, max_length=50)),
                ("marital_status", models.CharField(blank=True, max_length=50)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("forms_of_violence", models.TextField(blank=True)),
                ("reporting_violence", models.BooleanField(default=False)),
                ("vulnerable_places", models.TextField(blank=True)),
                ("employment", models.CharField(blank=True, max_length=100)),
                ("physical_punishment", models.BooleanField(default=False)),
                ("believe_in_child_punishment", models.BooleanField(default=False)),
                (
                    "effectiveness_positive_punishment",
                    models.CharField(blank=True, max_length=200),
                ),
                ("child_comforting", models.BooleanField(default=False)),
                ("impose_rules_to_child", models.BooleanField(default=False)),
                ("set_rules_with_child", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("school", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("age_group", models.CharField(blank=True, max_length=50)),
                ("disability_status", models.BooleanField(default=False)),
                ("knowledge_on_violence", models.BooleanField(default=False)),
                ("experienced_vac", models.BooleanField(default=False)),
                ("forms_of_violence", models.TextField(blank=True)),
                ("perpetrators", models.TextField(blank=True)),
                ("vulnerable_places", models.TextField(blank=True)),
                ("reporting_violence", models.BooleanField(default=False)),
                (
                    "effectiveness_reporting_system",
                    models.CharField(blank=True, max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("school", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("age_group", models.CharField(blank=True, max_length=50)),
                ("marital_status", models.CharField(blank=True, max_length=50)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("forms_of_violence", models.TextField(blank=True)),
                ("reporting_violence", models.BooleanField(default=False)),
                ("vulnerable_places", models.TextField(blank=True)),
                ("right_to_discipline_child", models.BooleanField(default=False)),
                (
                    "effective_handling_vac",
                    models.CharField(blank=True, max_length=200),
                ),
                ("training_received", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
